
version: '1'

services:
  app:
    container_name: ap
    build: .
    volumes:
      - .:/go/src/awesomeProject
    ports:
      - 5000:5000
  mongo:
    container_name: mongo
    image: mongo:4.0.10
    volumes:
      - ./data:/data
    ports:
      - 27017:27017